# Introduction to Python (Part 2)¶

## Create, Manipulate and Summarise Data

In [3]:
# Import necessary libraries
import numpy as np
import pandas as pd
import os
# from google.colab import files #Uncomment if you are using Google Colab
import io
import random
from scipy import stats

ModuleNotFoundError: No module named 'google.colab'

---
### Generating Numbers and Sequences

In [168]:
# 20 random numbers between 1 and 10 (inclusive)
x1 = np.random.randint(1, 11, size=20)
x1

array([ 4,  2,  7,  9,  1,  8,  3, 10,  1,  6,  8,  8,  3,  3, 10,  9,  9,
        1,  5,  7])

In [170]:
# 20 random numbers between 5 and 15 from a Uniform distribution
x2 = np.random.uniform(5, 15, 20)
x2

array([ 5.32885956,  6.51807645,  7.59665095, 10.18414605,  5.30643365,
       10.91441041,  7.11351389, 13.96687572, 14.0582654 , 11.45281275,
       11.02172551,  9.913455  ,  8.70739435, 14.14967467,  8.13346981,
       13.4515866 , 13.7557266 ,  5.0590237 , 10.66987235,  9.68769726])

In [172]:
# 20 random numbers from a normal distribution with mean=12 and sd=3
x3 = np.random.normal(loc=12, scale=3, size=20)
x3

array([ 8.52222934, 10.66292128,  9.4669066 , 11.34228147, 10.28836464,
       12.42473138, 12.77519061, 11.9396427 , 11.56057943, 15.55159201,
       14.6593878 ,  8.59794071, 11.68752408, 10.44154931, 18.2346599 ,
        6.00056609, 10.0507424 ,  9.16075551, 10.2692044 ,  8.77570694])

---

In [174]:
# A sequence from 1 to 20 with a 0.5 increment
x4 = np.arange(1, 20.5, 0.5)
x4

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [176]:
# Repeat the sequence {1,2,3,4,5} 5 times over
x5 = np.tile(np.arange(1,6), 5)
x5

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [178]:
# Repeat each element of the sequence {1,2,3,4,5} by 5 times
x6 = np.repeat(np.arange(1,6), 5)
x6

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [180]:
# Repeat each element of the sequence {1,2,3,4,5} by 3 times, then repeat that sequence 2 times
x7 = np.tile(np.repeat(np.arange(1,6), 3), 2)
x7

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1, 2, 2, 2, 3,
       3, 3, 4, 4, 4, 5, 5, 5])

---

In [184]:
# List first 10 letters (lowercase)
import string
list(string.ascii_lowercase[:10])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [186]:
# List first 10 letters (UPPERCASE)
list(string.ascii_uppercase[:10])

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

---
## Data Import/Export and Visualization

In [7]:
# To display an image in Jupyter (uncomment and set correct path if needed)
# from IPython.display import Image, display
# display(Image(filename='Importing_Data.png'))

# Uncomment the following if you are using Google Colab
# uploaded = files.upload()  # Interactive upload
# display(Image(next(iter(uploaded))))

In [5]:
# Uncomment if you are using notebook on your local machine
# Checking the current working directory
# %pwd

In [9]:
# Uncomment if you are using notebook on your local machine
# Make sure that the "os" package is imported
# os.chdir('/Users/mmasim/Downloads/MAT6202/Week1/') # Setting the current directory
# print(os.getcwd()) # Print to verify the current working directory

In [196]:
# Setting the default display style
pd.reset_option('^display.', silent=True)  # The '^' targets all display options

In [198]:
# Uncomment the following lines if you are using Google Colab
#uploaded = files.upload()
#ElderlyPopWA = pd.read_csv(io.BytesIO(uploaded['ElderlyPopWA-1.csv']))

# Uncomment the following lines if you are using notebook on your local machine
# Import CSV data (Set correct path if needed)
#ElderlyPopWA = pd.read_csv('ElderlyPopWA-1.csv')
#ElderlyPopWA # View the data

ParticipantID        Age        BMI       Waist         Hip     Tricep  \
0                1  75.013699  26.370318   89.000000   99.199997  21.799999   
1                2  76.367123  29.467426   99.699997  111.500000  21.299999   
2                3  75.624658  27.485648   88.800003  104.800003  28.799999   
3                4  73.868493  23.426871   82.800003   99.199997  22.799999   
4                5  75.526027  27.578124   88.599998  108.500000  27.799999   
..             ...        ...        ...         ...         ...        ...   
143            144  71.635616  30.266069  105.500000  106.000000  22.000000   
144            145  79.073973  25.423014   83.500000  101.000000  20.000000   
145            146  79.019178  28.662131   91.000000  108.800003  32.200001   
146            147  75.460274  31.523083   88.500000  115.000000  26.799999   
147            148  75.126027  34.284404  103.400002  126.500000  22.000000   

      ArmGirth  Pc_Body_Fat  
0    31.400000    40.703625  
1    29.799999    34.291783  
2    33.000000    35.608303  
3    28.900000    37.838579  
4    30.000000    43.883105  
..         ...          ...  
143  37.000000    41.985276  
144  30.000000    40.111623  
145  32.000000    41.095044  
146  34.200001    37.904763  
147  36.000000    45.751207  

[148 rows x 8 columns]

In [200]:
# Uncomment the following lines if you want to see all the rows and columns
# pd.set_option('display.max_rows', None)  # Show all rows
# pd.set_option('display.max_columns', None)  # Show all columns
display(ElderlyPopWA) # Using display function to view the data

ParticipantID        Age        BMI       Waist         Hip     Tricep  \
0                1  75.013699  26.370318   89.000000   99.199997  21.799999   
1                2  76.367123  29.467426   99.699997  111.500000  21.299999   
2                3  75.624658  27.485648   88.800003  104.800003  28.799999   
3                4  73.868493  23.426871   82.800003   99.199997  22.799999   
4                5  75.526027  27.578124   88.599998  108.500000  27.799999   
..             ...        ...        ...         ...         ...        ...   
143            144  71.635616  30.266069  105.500000  106.000000  22.000000   
144            145  79.073973  25.423014   83.500000  101.000000  20.000000   
145            146  79.019178  28.662131   91.000000  108.800003  32.200001   
146            147  75.460274  31.523083   88.500000  115.000000  26.799999   
147            148  75.126027  34.284404  103.400002  126.500000  22.000000   

      ArmGirth  Pc_Body_Fat  
0    31.400000    40.703625  
1    29.799999    34.291783  
2    33.000000    35.608303  
3    28.900000    37.838579  
4    30.000000    43.883105  
..         ...          ...  
143  37.000000    41.985276  
144  30.000000    40.111623  
145  32.000000    41.095044  
146  34.200001    37.904763  
147  36.000000    45.751207  

[148 rows x 8 columns]

In [202]:
ElderlyPopWA.head() # Show only the head

ParticipantID        Age        BMI      Waist         Hip     Tricep  \
0              1  75.013699  26.370318  89.000000   99.199997  21.799999   
1              2  76.367123  29.467426  99.699997  111.500000  21.299999   
2              3  75.624658  27.485648  88.800003  104.800003  28.799999   
3              4  73.868493  23.426871  82.800003   99.199997  22.799999   
4              5  75.526027  27.578124  88.599998  108.500000  27.799999   

    ArmGirth  Pc_Body_Fat  
0  31.400000    40.703625  
1  29.799999    34.291783  
2  33.000000    35.608303  
3  28.900000    37.838579  
4  30.000000    43.883105

In [206]:
# Export DataFrame to CSV
ElderlyPopWA.to_csv('ElderlyPopWA_updated.csv', index=False) # index = False ensures that no row numbers are entered

---
## Data Manipulation and Summaries

In [209]:
# Create BMI categories for the elderly female participants
# (Assumes ElderlyPopWA DataFrame is loaded)
mBMI = ElderlyPopWA['BMI'].max()
ElderlyPopWA['BMI_class'] = pd.cut(ElderlyPopWA['BMI'],
     bins=[0,23,31,mBMI],
     labels=['Underweight','Healthy_Weight','Overweight'])
ElderlyPopWA

ParticipantID        Age        BMI       Waist         Hip     Tricep  \
0                1  75.013699  26.370318   89.000000   99.199997  21.799999   
1                2  76.367123  29.467426   99.699997  111.500000  21.299999   
2                3  75.624658  27.485648   88.800003  104.800003  28.799999   
3                4  73.868493  23.426871   82.800003   99.199997  22.799999   
4                5  75.526027  27.578124   88.599998  108.500000  27.799999   
..             ...        ...        ...         ...         ...        ...   
143            144  71.635616  30.266069  105.500000  106.000000  22.000000   
144            145  79.073973  25.423014   83.500000  101.000000  20.000000   
145            146  79.019178  28.662131   91.000000  108.800003  32.200001   
146            147  75.460274  31.523083   88.500000  115.000000  26.799999   
147            148  75.126027  34.284404  103.400002  126.500000  22.000000   

      ArmGirth  Pc_Body_Fat       BMI_class  
0    31.400000    40.703625  Healthy_Weight  
1    29.799999    34.291783  Healthy_Weight  
2    33.000000    35.608303  Healthy_Weight  
3    28.900000    37.838579  Healthy_Weight  
4    30.000000    43.883105  Healthy_Weight  
..         ...          ...             ...  
143  37.000000    41.985276  Healthy_Weight  
144  30.000000    40.111623  Healthy_Weight  
145  32.000000    41.095044  Healthy_Weight  
146  34.200001    37.904763      Overweight  
147  36.000000    45.751207      Overweight  

[148 rows x 9 columns]

In [211]:
# Subsetting by a categorical variable
Underweight = ElderlyPopWA[ElderlyPopWA['BMI_class']=='Underweight']
Underweight

ParticipantID        Age        BMI      Waist         Hip     Tricep  \
16              17  77.728767  21.587388  81.699997   94.500000  21.400000   
17              18  74.791781  21.646093  78.400002   97.300003  15.300000   
32              33  72.641096  22.479339  85.699997   98.900002  33.599998   
34              35  70.386301  21.567706  76.800003   93.599998  18.900000   
35              36  77.715068  17.971159  77.199997   92.699997  17.400000   
41              42  76.531507  21.498099  75.000000   89.199997  20.000000   
49              50  70.304110  19.923934  79.900002   91.599998  24.000000   
51              52  75.589041  21.405747  77.900002   97.500000  22.799999   
55              56  71.805479  19.429245  72.400002   89.000000  23.200001   
59              60  75.747945  18.191916  66.000000   84.400002  10.100000   
60              61  72.969863  21.138016  73.599998   97.000000  15.000000   
62              63  70.449315  22.195921  78.300003   96.699997  17.100000   
64              65  73.227397  22.498228  88.199997   93.199997  23.400000   
67              68  78.939726  22.024043  72.500000   97.000000  12.800000   
76              77  75.871233  22.079348  82.699997   98.099998  33.200001   
80              81  70.556164  21.340539  78.500000   92.500000  21.400000   
88              89  72.484932  20.123532  80.500000   91.400002  20.799999   
106            107  78.619178  19.259212  66.599998   83.500000  11.600000   
107            108  76.317808  20.682747  72.699997   99.800003  23.600000   
113            114  77.191781  22.648129  81.900002   96.000000  30.400000   
116            117  78.460274  22.018367  86.800003   97.099998  26.400000   
124            125  74.268493  20.952528  71.500000   91.000000  14.000000   
131            132  74.493151  21.723813  77.000000   93.900002  19.400000   
135            136  70.942466  22.380074  73.500000   96.500000  27.600000   
137            138  71.463014  21.519471  71.000000   95.000000  36.000000   
141            142  73.545205  22.501425  77.900002  103.699997  27.200001   
142            143  73.109589  19.288318  69.000000   86.199997  21.200001   

      ArmGirth  Pc_Body_Fat    BMI_class  
16   24.299999    29.247140  Underweight  
17   26.500000    30.113362  Underweight  
32   28.900000    30.810804  Underweight  
34   26.700001    28.666182  Underweight  
35   22.799999    28.872756  Underweight  
41   26.299999    23.726984  Underweight  
49   28.200001    31.161761  Underweight  
51   27.700001    26.358967  Underweight  
55   25.500000    31.837319  Underweight  
59   22.100000    21.598322  Underweight  
60   25.000000    32.607499  Underweight  
62   28.100000    35.154460  Underweight  
64   29.000000    30.155273  Underweight  
67   27.200001    30.785029  Underweight  
76   28.000000    33.661167  Underweight  
80   25.500000    31.841935  Underweight  
88   26.500000    37.679148  Underweight  
106  24.000000    25.502146  Underweight  
107  28.000000    32.763892  Underweight  
113  30.000000    34.024833  Underweight  
116  27.200001    32.963658  Underweight  
124  27.700001    32.477179  Underweight  
131  25.700001    29.509587  Underweight  
135  27.900000    31.030551  Underweight  
137  29.799999    30.005628  Underweight  
141  27.299999    42.197660  Underweight  
142  25.500000    27.621482  Underweight

In [213]:
# Subsetting by a categorical variable
# Selecting more than one value
Unhealthy_weight = ElderlyPopWA[ElderlyPopWA['BMI_class'].isin(['Underweight','Overweight'])]
Unhealthy_weight

ParticipantID        Age        BMI       Waist         Hip     Tricep  \
5                6  74.095890  35.938673  106.800003  113.800003  29.000000   
8                9  78.630137  34.187393  100.000000  116.000000  37.799999   
14              15  79.967123  31.406251   97.400002  116.900002  26.600000   
16              17  77.728767  21.587388   81.699997   94.500000  21.400000   
17              18  74.791781  21.646093   78.400002   97.300003  15.300000   
21              22  79.158904  31.393820   93.900002  116.800003  38.200001   
22              23  76.224658  32.268119  103.199997  117.099998  37.000000   
25              26  74.843836  33.645787  106.000000  120.500000  32.000000   
26              27  72.616438  32.551739   94.500000  114.599998  21.799999   
32              33  72.641096  22.479339   85.699997   98.900002  33.599998   
34              35  70.386301  21.567706   76.800003   93.599998  18.900000   
35              36  77.715068  17.971159   77.199997   92.699997  17.400000   
37              38  75.786301  31.077857   96.300003  109.400002  35.200001   
41              42  76.531507  21.498099   75.000000   89.199997  20.000000   
47              48  77.331507  32.399199  100.199997  117.000000  40.000000   
48              49  71.898630  31.717704  102.800003  113.699997  42.000000   
49              50  70.304110  19.923934   79.900002   91.599998  24.000000   
51              52  75.589041  21.405747   77.900002   97.500000  22.799999   
52              53  73.043836  33.879110  107.000000  127.500000  38.599998   
55              56  71.805479  19.429245   72.400002   89.000000  23.200001   
59              60  75.747945  18.191916   66.000000   84.400002  10.100000   
60              61  72.969863  21.138016   73.599998   97.000000  15.000000   
62              63  70.449315  22.195921   78.300003   96.699997  17.100000   
64              65  73.227397  22.498228   88.199997   93.199997  23.400000   
67              68  78.939726  22.024043   72.500000   97.000000  12.800000   
76              77  75.871233  22.079348   82.699997   98.099998  33.200001   
80              81  70.556164  21.340539   78.500000   92.500000  21.400000   
81              82  73.430137  34.069877  105.300003  119.599998  35.000000   
82              83  72.720548  31.565607   98.000000  105.300003  35.200001   
87              88  71.180822  32.626572   95.400002  105.199997  37.599998   
88              89  72.484932  20.123532   80.500000   91.400002  20.799999   
106            107  78.619178  19.259212   66.599998   83.500000  11.600000   
107            108  76.317808  20.682747   72.699997   99.800003  23.600000   
113            114  77.191781  22.648129   81.900002   96.000000  30.400000   
115            116  76.249315  33.414258  106.099998  120.400002  36.400002   
116            117  78.460274  22.018367   86.800003   97.099998  26.400000   
117            118  71.978082  35.081329   93.800003  128.899994  31.799999   
119            120  76.457534  33.279307   95.300003  114.699997  34.200001   
124            125  74.268493  20.952528   71.500000   91.000000  14.000000   
126            127  73.980822  35.838077  110.800003  127.300003  40.000000   
131            132  74.493151  21.723813   77.000000   93.900002  19.400000   
135            136  70.942466  22.380074   73.500000   96.500000  27.600000   
137            138  71.463014  21.519471   71.000000   95.000000  36.000000   
140            141  71.013699  35.054811  110.500000  127.500000  41.799999   
141            142  73.545205  22.501425   77.900002  103.699997  27.200001   
142            143  73.109589  19.288318   69.000000   86.199997  21.200001   
146            147  75.460274  31.523083   88.500000  115.000000  26.799999   
147            148  75.126027  34.284404  103.400002  126.500000  22.000000   

      ArmGirth  Pc_Body_Fat    BMI_class  
5    39.400002    46.771411   Overweight  
8    37.400002    40.142492   Overweight  
14  

In [221]:
# Select a subset
# Select those under 75 years of age, and select all columns
Age_LT75 = ElderlyPopWA[ElderlyPopWA['Age'] < 75] 
Age_LT75

ParticipantID        Age        BMI       Waist         Hip     Tricep  \
3                4  73.868493  23.426871   82.800003   99.199997  22.799999   
5                6  74.095890  35.938673  106.800003  113.800003  29.000000   
6                7  74.810959  27.443247   83.900002  101.800003  30.000000   
7                8  74.079452  28.180084   90.000000  109.900002  22.200001   
9               10  73.871233  24.062499   85.699997   94.300003  17.200001   
..             ...        ...        ...         ...         ...        ...   
139            140  73.556164  26.579920   87.300003  101.599998  36.799999   
140            141  71.013699  35.054811  110.500000  127.500000  41.799999   
141            142  73.545205  22.501425   77.900002  103.699997  27.200001   
142            143  73.109589  19.288318   69.000000   86.199997  21.200001   
143            144  71.635616  30.266069  105.500000  106.000000  22.000000   

      ArmGirth  Pc_Body_Fat       BMI_class  
3    28.900000    37.838579  Healthy_Weight  
5    39.400002    46.771411      Overweight  
6    32.599998    38.378474  Healthy_Weight  
7    31.500000    40.729741  Healthy_Weight  
9    28.100000    33.857199  Healthy_Weight  
..         ...          ...             ...  
139  31.400000    39.917206  Healthy_Weight  
140  38.500000    45.379558      Overweight  
141  27.299999    42.197660     Underweight  
142  25.500000    27.621482     Underweight  
143  37.000000    41.985276  Healthy_Weight  

[89 rows x 9 columns]

In [225]:
# Select a subset
# Select those under 75 years of age, but select fewer columns only
# use : instead of ['BMI', 'Waist'] incase if all the columns are to be selected
Age_LT75 = ElderlyPopWA.loc[ElderlyPopWA['Age']<75, ['BMI', 'Waist']]; Age_LT75

BMI       Waist
3    23.426871   82.800003
5    35.938673  106.800003
6    27.443247   83.900002
7    28.180084   90.000000
9    24.062499   85.699997
..         ...         ...
139  26.579920   87.300003
140  35.054811  110.500000
141  22.501425   77.900002
142  19.288318   69.000000
143  30.266069  105.500000

[89 rows x 2 columns]

In [227]:
# Select a subset by using "~" operator
# Select those that are not under 75 years of age.
Age_GTE75 = ElderlyPopWA[~(ElderlyPopWA['Age'] < 75)] 
Age_GTE75

ParticipantID        Age        BMI       Waist         Hip     Tricep  \
0                1  75.013699  26.370318   89.000000   99.199997  21.799999   
1                2  76.367123  29.467426   99.699997  111.500000  21.299999   
2                3  75.624658  27.485648   88.800003  104.800003  28.799999   
4                5  75.526027  27.578124   88.599998  108.500000  27.799999   
8                9  78.630137  34.187393  100.000000  116.000000  37.799999   
10              11  79.734247  29.174885  102.000000  107.000000  12.500000   
12              13  75.876712  28.650692   90.000000  105.800003  25.100000   
13              14  75.375342  28.269917   90.699997  110.000000  25.000000   
14              15  79.967123  31.406251   97.400002  116.900002  26.600000   
15              16  78.775342  25.189543   85.099998  106.599998  27.700001   
16              17  77.728767  21.587388   81.699997   94.500000  21.400000   
21              22  79.158904  31.393820   93.900002  116.800003  38.200001   
22              23  76.224658  32.268119  103.199997  117.099998  37.000000   
23              24  78.484932  27.063534   89.900002  104.000000  32.599998   
29              30  75.221918  28.381114   87.500000  111.000000  27.000000   
31              32  78.183562  27.337780  100.800003  108.000000  34.799999   
35              36  77.715068  17.971159   77.199997   92.699997  17.400000   
37              38  75.786301  31.077857   96.300003  109.400002  35.200001   
41              42  76.531507  21.498099   75.000000   89.199997  20.000000   
43              44  78.210959  28.263529   91.000000  105.500000  22.200001   
45              46  76.457534  25.283639   90.000000  104.099998  23.799999   
46              47  77.753425  26.171610   82.300003  110.699997  32.799999   
47              48  77.331507  32.399199  100.199997  117.000000  40.000000   
50              51  78.180822  24.616526   87.400002  101.800003  25.400000   
51              52  75.589041  21.405747   77.900002   97.500000  22.799999   
56              57  75.172603  27.630942   95.000000  109.500000  28.799999   
59              60  75.747945  18.191916   66.000000   84.400002  10.100000   
61              62  75.597260  26.099433   81.000000  103.000000  25.000000   
67              68  78.939726  22.024043   72.500000   97.000000  12.800000   
68              69  77.821918  25.170122   79.400002  102.400002  28.799999   
70              71  78.035616  28.370359   94.599998  103.000000  38.400002   
75              76  75.273973  26.547092   89.800003   95.599998  30.600000   
76              77  75.871233  22.079348   82.699997   98.099998  33.200001   
78              79  75.487671  24.187531   72.400002   92.699997  37.200001   
83              84  77.690411  26.246777   97.400002  109.699997  37.599998   
89              90  77.032877  24.358723   86.800003   98.500000  36.599998   
94              95  77.041096  23.923016   82.500000   97.900002  42.200001   
95              96  76.019178  24.281874   87.500000   96.500000  26.000000   
100            101  77.791781  26.137717   88.300003  103.000000  23.200001   
104            105  78.852055  27.589560   87.400002  106.000000  31.200001   
105            106  77.980822  26.761259   85.800003   96.199997  20.799999   
106            107  78.619178  19.259212   66.599998   83.500000  11.600000   
107            108  76.317808  20.682747   72.699997   99.800003  23.600000   
108            109  76.750685  26.427789   90.500000  113.000000  33.400002   
110            111  75.032877  24.722123   88.000000   97.000000  37.599998   
113            114  77.191781  22.648129   81.900002   96.000000  30.400000   
114            115  75.054795  26.366049   91.000000  104.000000  36.599998   
115            116  76.249315  33.414258  106.099998  120.400002  36.400002   
116            117  78.460274  22.018367   86.800003   97.099998  26.400000   
119            120  76.457534  33.279307   95.300003  1

---
## Data Statistics and Analysis

### Measure the centre

In [24]:
ElderlyPopWA['Age'].mean()

74.31747500952703

In [26]:
ElderlyPopWA['Age'].median()

74.08767123

### Measure the Shape

In [29]:
ElderlyPopWA['Age'].std()

2.5966766807133146

In [31]:
ElderlyPopWA['Age'].min(), ElderlyPopWA['Age'].max()

(70.30410959, 79.96712329)

In [33]:
ElderlyPopWA['Age'].quantile([0.25,0.5,0.75])

0.25    72.108219
0.50    74.087671
0.75    76.266438
Name: Age, dtype: float64

In [35]:
np.percentile(ElderlyPopWA['Age'], [0,25,50,75,100])

array([70.30410959, 72.10821918, 74.08767123, 76.26643836, 79.96712329])

### Measure the Spread

In [40]:
# Skewness and kurtosis (requires scipy.stats)
stats.skew(ElderlyPopWA['Age'])

-0.9789481376381994

In [42]:
# Skewness and kurtosis (requires scipy.stats)
stats.kurtosis(ElderlyPopWA['Age'])

-0.9789481376381994

#### Column-wise opeations

In [46]:
# Column means
ElderlyPopWA.iloc[:,1:8].mean()

Age             74.317475
BMI             26.628860
Waist           88.413514
Hip            104.329730
Tricep          28.861486
ArmGirth        31.249324
Pc_Body_Fat     38.294585
dtype: float64

In [54]:
# Apply mean column-wise using axis=0, axis=1 implies row-wise
ElderlyPopWA.iloc[:,1:8].apply(np.mean, axis=0)

Age             74.317475
BMI             26.628860
Waist           88.413514
Hip            104.329730
Tricep          28.861486
ArmGirth        31.249324
Pc_Body_Fat     38.294585
dtype: float64

In [50]:
# # Apply std column-wise using axis=0, axis=1 implies row-wise
ElderlyPopWA.iloc[:,1:8].apply(np.std, axis=0)

Age            2.587889
BMI            3.911865
Waist          9.050576
Hip            8.956648
Tricep         7.628950
ArmGirth       3.376639
Pc_Body_Fat    5.284628
dtype: float64

#### Frequency and proportion tables

In [62]:
# Number of participants in each BMI Class
BMI_freq = ElderlyPopWA['BMI_class'].value_counts(); BMI_freq

BMI_class
Healthy_Weight    100
Underweight        27
Overweight         21
Name: count, dtype: int64

In [66]:
# Proportions of the samples for each BMI Class
BMI_prop = ElderlyPopWA['BMI_class'].value_counts(normalize=True); BMI_prop

BMI_class
Healthy_Weight    0.675676
Underweight       0.182432
Overweight        0.141892
Name: proportion, dtype: float64

In [68]:
# Create another categorical variable, i.e. age group
ElderlyPopWA['Age_grp'] = pd.cut(ElderlyPopWA['Age'], [0,74.99,100], labels=['<75years','75+years'])
tab = pd.crosstab(ElderlyPopWA['Age_grp'], ElderlyPopWA['BMI_class']); tab

BMI_class  Underweight  Healthy_Weight  Overweight
Age_grp                                           
<75years            16              62          11
75+years            11              38          10

In [70]:
# Checking the propotion of new variable, age group
tab.div(tab.sum(axis=1), axis=0)  # Proportions by row

BMI_class  Underweight  Healthy_Weight  Overweight
Age_grp                                           
<75years      0.179775        0.696629    0.123596
75+years      0.186441        0.644068    0.169492

In [72]:
tab.div(tab.sum(axis=0), axis=1)  # Proportions by column

BMI_class  Underweight  Healthy_Weight  Overweight
Age_grp                                           
<75years      0.592593            0.62     0.52381
75+years      0.407407            0.38     0.47619

In [74]:
tab/tab.values.sum()  # Proportions relative to overall sample size

BMI_class  Underweight  Healthy_Weight  Overweight
Age_grp                                           
<75years      0.108108        0.418919    0.074324
75+years      0.074324        0.256757    0.067568

In [80]:
# Summarise waist circumference by BMI class
ElderlyPopWA.groupby('BMI_class', observed=True)['Waist'].mean() # Compute the mean

BMI_class
Underweight        76.785185
Healthy_Weight     88.968000
Overweight        100.723810
Name: Waist, dtype: float64

In [84]:
ElderlyPopWA.groupby('BMI_class', observed=True)['Waist'].std() # Compute the standard deviation

BMI_class
Underweight       5.717362
Healthy_Weight    6.081282
Overweight        6.115383
Name: Waist, dtype: float64

In [96]:
# Summarise waist circumference by BMI class and age group
ElderlyPopWA.groupby(['BMI_class','Age_grp'], observed=True)['Waist'].mean() # Compute the mean

BMI_class       Age_grp 
Underweight     <75years     77.012500
                75+years     76.454545
Healthy_Weight  <75years     88.988710
                75+years     88.934211
Overweight      <75years    102.809092
                75+years     98.430000
Name: Waist, dtype: float64

In [100]:
ElderlyPopWA.groupby(['BMI_class','Age_grp'], observed=True)['Waist'].std() # Compute the standard deviation

BMI_class       Age_grp 
Underweight     <75years    5.188175
                75+years    6.664138
Healthy_Weight  <75years    6.227915
                75+years    5.916412
Overweight      <75years    6.333317
                75+years    5.232387
Name: Waist, dtype: float64

In [104]:
# Mean waist circumference by BMI Class, using apply
ElderlyPopWA.groupby('BMI_class', observed=True)['Waist'].apply(np.mean)

BMI_class
Underweight        76.785185
Healthy_Weight     88.968000
Overweight        100.723810
Name: Waist, dtype: float64

In [106]:
ElderlyPopWA.groupby(['BMI_class','Age_grp'], observed=True)['Waist'].apply(np.mean) #BMI CLass and Age Group

BMI_class       Age_grp 
Underweight     <75years     77.012500
                75+years     76.454545
Healthy_Weight  <75years     88.988710
                75+years     88.934211
Overweight      <75years    102.809092
                75+years     98.430000
Name: Waist, dtype: float64

In [108]:
# Round proportions
np.round(ElderlyPopWA['BMI_class'].value_counts(normalize=True), 3)

BMI_class
Healthy_Weight    0.676
Underweight       0.182
Overweight        0.142
Name: proportion, dtype: float64

In [110]:
# Chained operations with pandas
ElderlyPopWA['BMI_class'].value_counts(normalize=True).round(3) # Round to 3 dp

BMI_class
Healthy_Weight    0.676
Underweight       0.182
Overweight        0.142
Name: proportion, dtype: float64

---
### Functions in Python

In [112]:
# Function definition and usage in Python
def Greeting():
    print("Hello! My name is XXXX")

In [114]:
Greeting() # Calling a function

Hello! My name is XXXX


In [116]:
def add3(x):
    return x + 3

In [118]:
add3(5) # Passing parameters

8

In [120]:
add3(10)

13

In [122]:
add3(15)

18

In [124]:
def add_mult(x, y):
    sum_xy = x + y
    prod_xy = x * y
    ratio_xy = x / y
    return sum_xy, prod_xy, ratio_xy

In [126]:
x = 3
y = 4
print(add_mult(x, y))

(7, 12, 0.75)


In [128]:
add_mult(x=3, y=4)

(7, 12, 0.75)

In [130]:
add_mult(y=4, x=3)

(7, 12, 0.75)

In [132]:
add_mult(3, 4)

(7, 12, 0.75)

---
### Control Stuctures *(IF ELSE Statements)*

In [135]:
# If statement: check if x is odd
x = 5
if x % 2 != 0:
    print(f'{x} is an odd integer')

5 is an odd integer


In [137]:
# If-else statement: check if x is odd or even
x = 10
if x % 2 != 0:
    print(f'{x} is an odd integer')
else:
    print(f'{x} is an even integer')

10 is an even integer


In [139]:
# Nested if-elif-else for grading
score = 65
if score < 0:
    print('Invalid score!')
elif score < 50:
    print('Your final grade is N.')
elif score < 60:
    print('Your final grade is P.')
elif score < 70:
    print('Your final grade is C.')
elif score < 80:
    print('Your final grade is D.')
elif score <= 100:
    print('Your final grade is HD.')
else:
    print('Invalid score!')

Your final grade is C.


In [141]:
# For loop from 1 to 10
for I in range(1, 11):
    print(I)

1
2
3
4
5
6
7
8
9
10


In [147]:
# For loop to print mean of columns 2 to 8 (assumes ElderlyPopWA is loaded)
dat = ElderlyPopWA.copy()
for J in range(1, 8):
    print(dat.iloc[:, J].mean().round(3))

74.317
26.629
88.414
104.33
28.861
31.249
38.295


In [149]:
# For loop: print numbers divisible by 7 from 1 to 100
for I in range(1, 101):
    if I % 7 == 0:
        print(I)

7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [151]:
# For loop: print first 10 numbers divisible by 13 between 500 and 800
count = 0
for I in range(500, 801):
    if I % 13 == 0:
        print(I)
        count += 1
    if count == 10:
        break

507
520
533
546
559
572
585
598
611
624
