# **Introduction to Python (Part 1)**

**Python** is a high-level, versatile, and easy-to-read programming language that is widely used in data science, web development, automation, and software engineering. It emphasizes code readability with a simple syntax, making it an excellent choice for beginners. Python supports multiple programming paradigms—including procedural, object-oriented, and functional programming—and has a vast ecosystem of libraries and tools that make it powerful for advanced applications in research and industry. For a master's level student, Python offers a strong foundation for both academic and practical problem-solving in computing.

---
## **1. Fundamentals of Programming in Python**

ٰٰ**NumPY** is a foundational Python library for numerical computing.
Provides: Fast multi-dimensional arrays (ndarray), Mathematical operations (linear algebra, statistics, etc.), Efficient data storage and vectorized operations.

**Pandas** is built on NumPy for data manipulation and analysis.
Provides: DataFrames (tabular data) and Series (1D arrays), Tools for cleaning, transforming, and analyzing structured data, Time series handling, I/O (CSV/Excel), and merging datasets.

In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd

---
### **1.1 Variable Assignment**

In mathematics and statistics, a variable represents a symbol that can take on different values. In Python, a variable is a name that refers to a value (or object) stored in memory. You can use a variable to store:

- Primitive data (like numbers or strings)
- Data structures (like lists or dictionaries)
- Functions
- Objects from custom classes
- Even plots or models (via external libraries)

You can later use the variable’s name to retrieve or manipulate what it refers to.

A variable name must start with a letter (lowercase or uppercase) or an underscore (_). Variable names cannot be a Python keyword (e.g., if, else, for, while, etc.).

Python uses the = symbol for assignment. In the example below, the number 35 is assigned to the variable x. This means “let x point to the object 35.” Note that when you run this command, the object or variable x is created but nothing will be displayed.

In [6]:
# Assign a value to x
x = 35

To recall or print out the value that is assigned to variable x, you just need to run variable name as a command.

In [9]:
# Display x
x

35

You can overwrite the stored value by assigning another value to the same variable. For example:

In [12]:
# Assign a new value to x and display
x = 18
x

18

Suppose we want to add 8 to x and store the sum in a new object, say y. This can be done as follows.

In [15]:
# Adds 8 to the value of x and stores the result in y
y = x + 8
y

26

Suppose now we have a linear equation given by y = 3x + 5. Since x = 18, then we have,

In [18]:
# Multiplies x by 3, adds 5, and stores the result in y
y = 3 * x + 5
y

59

---

When coding, it is always a good idea to give meaningful names to variables and better yet, ones that are self explanatory. Providing meaningful names to variables will help the reader and reduce the amount of commentaries required. For example, suppose we want to calculate the area of a circle (i.e. 𝜋𝑟2), given that its diameter is 10 cm. Here we have,

In [22]:
# Area of a circle given diameter
diam = 10  # diameter = 10 cm
radius = diam / 2  # radius is half of the diameter
area_circle = np.pi * radius ** 2  # area of the circle
area_circle

78.53981633974483

---

### **1.2 Data Types**

There are five basic data types in Python.
- Integer (int)
- Float (float)
- Boolean (bool)
- String (str)
- Complex (complex)

But we will focus on the four most commonly used in this session, i.e. **Interger, Float, Boolean and String.** The *complex* type, such as 2 + 3j, is used to handle complex numbers that include both real and imaginary parts, which we will not discuss here.


#### **1.2.1 Integer (whole numbers): int**
The *Integer* type is used for whole numbers such as 5 or -100.

In [28]:
5 # Positive whole number as constact

5

In [30]:
-3 # Negative whole number as constant

-3

In [32]:
x = 5 # Assignment of whole number makes x as int by default
x

5

In [34]:
type(x) # Confirming the data type

int

#### **1.2.2 Floating-point numbers: float**
The float type represents real numbers with decimal points, like 3.14 or -0.01.

In [37]:
5.5 # Positive floating-point constant

5.5

In [39]:
-2.75 # Negative floating-point constant

-2.75

In [41]:
np.pi # Display the value of 𝜋 using numpy object 'np'

3.141592653589793

We can also perform mathematical operations on the *Integer* and *Float*, just as you would do in a calculator. Only *float* type numbers are shown as an example.

In [44]:
# Basic arithmetic operations
5.5 + 2.7  # Addition

8.2

In [46]:
5.5 - 2.7  # Subtraction

2.8

In [48]:
y = 5.5 / 2; y  # Division

2.75

In [50]:
type(y) # Note that float and int were involved in the operation

float

In [52]:
5.5 * 2  # Multiplication

11.0

In [54]:
5.5 ** 2  # Squaring

30.25

In [56]:
5.5 ** 4  # To the power of 4

915.0625

In [58]:
np.sqrt(5.5)  # Square root

2.345207879911715

In [60]:
np.exp(5.5)  # Exponential

244.69193226422038

In [62]:
np.log(5.5)  # Natural log

1.7047480922384253

#### **1.2.3 Logical Operators (Boolean)**
A logical value is to indicate whether an item/statement is TRUE or FALSE, i.e. a Boolean value. Python provides several operators for performing logical operations. Here's a complete list:

In [70]:
# Basic Logical Operators
True and False # Logical AND results in "False" outcome

False

In [72]:
True or False # Logical OR results in "True" outcome

True

In [74]:
not True # Logical NOT returns "False" in the outcome

False

In [76]:
# Bitwise Logical Operators (for integers). These perform logical operations bit-by-bit:
5 & 3  # & is Bitwise AND, Returns 1 (0101 & 0011 = 0001)

1

In [78]:
5 | 3  # | is Bitwise OR, Returns 7 (0101 | 0011 = 0111)

7

In [80]:
5 ^ 3  # ^ is Bitwise XOR, Returns 6 (0101 ^ 0011 = 0110)

6

In [82]:
~5  # ~ is Bitwise NOT, Returns -6 (inverts all bits)

-6

*Comparison* Operators return True/False (Boolean) based on the following operators:

== - Equal to

!= - Not equal to

\> - Greater than

< - Less than

\>= - Greater than or equal to

<= - Less than or equal to

In [85]:
# Logical comparisons Examples
5 == 5  # Does 5 equal 5?

True

In [87]:
5 == 2  # Does 5 equal 2?

False

In [89]:
5 != 2  # Does 5 not equal 2?

True

In [91]:
5 > 2  # Is 5 greater than 2?

True

In [93]:
5 >= 2  # Is 5 greater than or equals to 2

True

In [95]:
5 < 2  # Is 5 less than 2?

False

In [97]:
5 <= 2  # Is 5 less than or equals to 2

False

In [99]:
# Logical operations combining logical operators and comaprison operators
(5 > 2) and (5 > 4)

True

In [101]:
(5 > 2) and (5 < 4)

False

In [103]:
(5 > 2) or (5 < 4)

True

In [109]:
# Identity Operators
# is - True if same object
x is y # x and y are different, "Flase" is returned

False

In [111]:
x is not y # 'is not' - True if different objects

True

In [107]:
# Membership Operators
a = [1,2,3]
b = 2
b in a # in - True if value found in sequence

True

In [113]:
b not in a # 'not in' - True if value not found in sequence

False

#### **1.2.4 Strings (Textual data): str**
A character in Python is represented as a **string** value *(str)*, defined using quotes (" " or ' '). A string can contain numbers (e.g. "1", "2", "3"), letters (e.g. "a", "b", "C"), symbols (e.g. "#", "$", "@"), or a combination of these, such as words or sentences. It’s important to note that if a number is stored as a string, you cannot perform mathematical operations on it directly. For example, "5" is a string, not a number, so trying to add it to an integer will result in an error. To use it in calculations, you must first convert it to a numeric type using functions like int() or float().

In [116]:
# String examples
'a'

'a'

In [118]:
"abc123"

'abc123'

In [120]:
'apples'

'apples'

In [122]:
'I hate apples'

'I hate apples'

In [124]:
# Multiple strings as separate commonds (separated by ;) in one cell, Only prints the last literal
'a'; 'abc' ; 'apples'; 'I hate apples'

'I hate apples'

In [126]:
# Using 'print' command if you want to display multiple objects in the same cell
print('a'); print("abc") ; 'apples'; 'I hate apples'

a
abc


'I hate apples'

---
### **1.3 Data Structures**
Data structures are tools for holding multiple values. In data analysis, one typically works with groups of numbers and/or characters, and rarely with single values one-at-a-time. Data structures allows us to store and manipulate multiple or groups of values simultaneously. The fundamental data structures in Python that we will discuss here include lists, arrays, categorical data (levels), matrices, and data frames.

#### **1.3.1 Creating sequences (Lists and arrays)**
A sequence *list* can be a collection of elements of the same or different data types.

In [130]:
[]  # A null (empty) list

[]

In [132]:
a = [1, 2, 3]  # A numeric list
a

[1, 2, 3]

In [134]:
['a', 'b', 'c']  # A character list

['a', 'b', 'c']

In [136]:
[True, False, False]  # A logical list

[True, False, False]

Let us create a *list* containing the integers from 1 to 5.

In [139]:
# Create a list from 1 to 5
a = list(range(1, 6))
a

[1, 2, 3, 4, 5]

We use square brackets, i.e. [.], if we wish to access particular element(s) within the list, rather than the whole list. Remember, Python is 0-indexed, which means that the first element in the list is indexed as 0.

In [142]:
# Accessing elements in a list (Python is 0-indexed)
a[1]  # 2nd element

2

In [144]:
a[2]  # 3rd element

3

In [146]:
a[2:5]  # 3rd to 5th element

[3, 4, 5]

In [148]:
[a[1], a[4]]  # 2nd and 5th elements

[2, 5]

In [150]:
z = [1 , 'a', True]; z # list of different data types

[1, 'a', True]

In [152]:
type(z) # confirming the data type of z

list

In [154]:
# Create a new list b containing the integers 6, 7, 8, 9, 10
b = list(range(6, 11))
b

[6, 7, 8, 9, 10]

In [156]:
# Combine lists a and b
c = a + b
c

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [158]:
c = a * 4; c # Appending the list 'a' four times and assigning it to 'c', then display 'c'

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

**Pro Tip:** The variable name simply points to an object in memory. This affects mutability:

In [161]:
a = [1, 2, 3]
b = a        # b points to the same list as a
b.append(4)
a            # Display a, Output: [1, 2, 3, 4]

[1, 2, 3, 4]

---
We have to convert list in to **arrays**, if we have to perform numerical operations on them. Arrays are *ordered collections* of items (usually of the same type) stored in *contiguous memory*. Unlike lists, arrays are optimized for numerical operation.

In [164]:
# Element-wise operations using numpy arrays
a_np = np.array(a)
b_np = np.array(b)
a_np * 0.25  # Multiply elements of a by 0.25

array([0.25, 0.5 , 0.75, 1.  ])

In [166]:
a_np + b_np  # Add elements of a and b

array([2, 4, 6, 8])

In [168]:
b_np - a_np  # Subtract elements of a from b

array([0, 0, 0, 0])

In [170]:
a_np * b_np  # Multiply elements of a and b

array([ 1,  4,  9, 16])

In [172]:
b_np / a_np  # Divide elements of b by elements of a

array([1., 1., 1., 1.])

#### **1.3.2 Categorical Data in Python using Pandas**
Categorical data in pandas refers to a data type used for variables that take on a limited, fixed set of possible values (categories). Examples include:

Gender: ['Male', 'Female', 'Other']

Product Categories: ['Electronics', 'Clothing', 'Furniture']

Survey Ratings: ['Low', 'Medium', 'High']

In [175]:
f1 = pd.Categorical([1, 2, 3, 4, 5])
f1

[1, 2, 3, 4, 5]
Categories (5, int64): [1, 2, 3, 4, 5]

In [177]:
f2 = pd.Categorical(['Male', 'Female', 'Female', 'Male', 'Female'])
f2

['Male', 'Female', 'Female', 'Male', 'Female']
Categories (2, object): ['Female', 'Male']

In [179]:
f3 = pd.Categorical(['L', 'M', 'H', 'H', 'M', 'L'])
f3

['L', 'M', 'H', 'H', 'M', 'L']
Categories (3, object): ['H', 'L', 'M']

By default, categories follow lexicographical (alphabetical) order when created. However, the order can be explicitly defined if needed.

In [182]:
# Reorder the levels of f3
f3 = pd.Categorical(f3, categories=['L', 'M', 'H'], ordered=True)
f3

['L', 'M', 'H', 'H', 'M', 'L']
Categories (3, object): ['L' < 'M' < 'H']

#### **1.3.3 Matrices**
A matrix is a two-dimensional rectangular array of numbers, symbols, or expressions arranged in rows and columns. It is a fundamental structure in linear algebra, widely used in mathematics, physics, engineering, and data science (e.g., machine learning, image processing).

We can create matrix using 'arrange' function for numPY package.

In [185]:
# Create a 3x3 matrix, filled column-wise (default in numpy)
Mat_A = np.arange(1, 10).reshape((3, 3), order='F')
Mat_A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [187]:
# Create a 3x3 matrix, filled row-wise
Mat_B = np.arange(1, 10).reshape((3, 3), order='C')
Mat_B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
# Create a 3x3 matrix, column-wise (explicit)
Mat_A = np.arange(1, 10).reshape((3, 3), order='F')
Mat_A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Another way to create a matrix, is by **binding multiple arrays** of the same length together. We can either bind the vectors together as column arrays using the **np.column_stack(.)** command, or as row arrays using the **np.row_stack(.)** command.

In [192]:
# Bind arrays as columns and rows
a1 = np.array([1, 2, 3])  # Array 1
a2 = np.array([4, 5, 6])  # Array 2
a3 = np.array([7, 8, 9])  # Array 3
Mat_A = np.column_stack((a1, a2, a3))  # as columns
Mat_A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [194]:
Mat_B = np.row_stack((a1, a2, a3))  # as rows
Mat_B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The elements of two or more matrices can be multiplied together only if they have the same dimension. Since Mat.A and Mat.B are both 3 × 3 matrices, we can multiply them by one another. Note that the multiplication is done element-to-element. In this instance, A × B = B × A.

In [197]:
# Element-wise multiplication
Mat_A * Mat_B

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [199]:
# Element-wise multiplication
Mat_B * Mat_A

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

However in matrix multiplication, say A × B, the number of columns in matrix A must equal the number of rows in matrix B, and each row of matrix A are multiplied by each column of matrix B, and summed. Click here for a Khan Academy online tutorial in manual matrix multiplication. Matrix multiplication in Python is performed using the @ command. In matrix multiplication, A × B ≠ B × A.

In [202]:
# Matrix multiplication
Mat_A @ Mat_B  # A matrix multiply B

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [204]:
Mat_B @ Mat_A  # B matrix multiply A

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

To access the elements of a matrix, say A, we need to specify the corresponding row(s) and columns(s) within the square brackets, i.e. A[row(s),column(s)]. If the rows are not specified, but the columns are, then all the rows will be extracted and vice versa.

Here are some examples.

In [207]:
# Accessing elements in a matrix (Python is 0-indexed)
Mat_A[1, 2]  # element in row 2, column 3

8

In [209]:
Mat_A[0:2, 2]  # rows 1 and 2, column 3

array([7, 8])

In [211]:
Mat_A[0, 1:3]  # row 1, columns 2 and 3

array([4, 7])

In [213]:
Mat_A[0, :]  # all elements in row 1

array([1, 4, 7])

In [215]:
Mat_A[:, 2]  # all elements in column 3

array([7, 8, 9])

In [217]:
Mat_A[:, [0, 2]]  # all elements in columns 1 and 3

array([[1, 7],
       [2, 8],
       [3, 9]])

In [219]:
Mat_A[:, 1:]  # all data except column 1

array([[4, 7],
       [5, 8],
       [6, 9]])

#### **1.3.4 DataFrame**
A DataFrame is a two-dimensional, tabular data structure (like a spreadsheet or SQL table) provided by the pandas library. It organizes data in rows and columns, where each column can hold a different data type (e.g., numbers, strings, dates). However, all columns must have the same length, and the elements within each column must be of the same type. DataFrames are the primary tool for data manipulation and analysis in Python.

In [222]:
# Create vectors for a DataFrame
Name = ['John', 'Sarah', 'Zach', 'Beth', 'Lachlan']  # Name - Character vector
Age = [35, 28, 33, 55, 43]  # Age - Numeric vector
Gender = pd.Categorical(['Male', 'Female', 'Male', 'Female', 'Male'])  # Gender - factor

Now we can combine the three vectors to form a data frame.

In [225]:
# Create a DataFrame
df = pd.DataFrame({'Name': Name, 'Age': Age, 'Gender': Gender})
df

Name  Age  Gender
0     John   35    Male
1    Sarah   28  Female
2     Zach   33    Male
3     Beth   55  Female
4  Lachlan   43    Male

We can add new columns(s) to an existing data frame by using either the direct assignment or pd.concat(.) command.

In [228]:
# Add new column to the DataFrame (Method 1)
Coffee_Drinker = [True, True, False, True, False]  # Drinks coffee? - logical vector
df1 = df.copy()
df1['Coffee_Drinker'] = Coffee_Drinker
df1

Name  Age  Gender  Coffee_Drinker
0     John   35    Male            True
1    Sarah   28  Female            True
2     Zach   33    Male           False
3     Beth   55  Female            True
4  Lachlan   43    Male           False

In [230]:
# Add new column to the DataFrame (Method 2)
df2 = pd.concat([df, pd.Series(Coffee_Drinker, name='Coffee_Drinker')], axis=1)
df2

Name  Age  Gender  Coffee_Drinker
0     John   35    Male            True
1    Sarah   28  Female            True
2     Zach   33    Male           False
3     Beth   55  Female            True
4  Lachlan   43    Male           False

Data frames are accessed in the same way as matrices.

In [233]:
# Accessing rows and columns in DataFrame
df.iloc[[0], 0:3]  # 1st row, columns 1-3

Name  Age Gender
0  John   35   Male

In [235]:
df.iloc[1:3, :]  # rows 2 and 3, all columns

Name  Age  Gender
1  Sarah   28  Female
2   Zach   33    Male

In [237]:
df.iloc[:, [0, 2]]  # all rows, columns 1 and 3

Name  Gender
0     John    Male
1    Sarah  Female
2     Zach    Male
3     Beth  Female
4  Lachlan    Male

In [239]:
# Accessing columns by name
df['Name']

0       John
1      Sarah
2       Zach
3       Beth
4    Lachlan
Name: Name, dtype: object

In [241]:
df[['Name', 'Gender']]

Name  Gender
0     John    Male
1    Sarah  Female
2     Zach    Male
3     Beth  Female
4  Lachlan    Male

In [243]:
# Access and display columns (Another way)
df.Name

0       John
1      Sarah
2       Zach
3       Beth
4    Lachlan
Name: Name, dtype: object

In [245]:
df.loc[:, 'Age']

0    35
1    28
2    33
3    55
4    43
Name: Age, dtype: int64

In [247]:
df.iloc[:, 2]  # All rows, Third column (position 2)

0      Male
1    Female
2      Male
3    Female
4      Male
Name: Gender, dtype: category
Categories (2, object): ['Female', 'Male']

In [249]:
# Add new variables to df and display
df['Coffee_Drinker'] = Coffee_Drinker
df

Name  Age  Gender  Coffee_Drinker
0     John   35    Male            True
1    Sarah   28  Female            True
2     Zach   33    Male           False
3     Beth   55  Female            True
4  Lachlan   43    Male           False

In [251]:
df['Diabetes'] = pd.Categorical(['Yes', 'No', 'No', 'No', 'Yes'])
df

Name  Age  Gender  Coffee_Drinker Diabetes
0     John   35    Male            True      Yes
1    Sarah   28  Female            True       No
2     Zach   33    Male           False       No
3     Beth   55  Female            True       No
4  Lachlan   43    Male           False      Yes

We can oberseve the structure of the DataFrame using info(.) command.

In [254]:
# Structure of DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype   
---  ------          --------------  -----   
 0   Name            5 non-null      object  
 1   Age             5 non-null      int64   
 2   Gender          5 non-null      category
 3   Coffee_Drinker  5 non-null      bool    
 4   Diabetes        5 non-null      category
dtypes: bool(1), category(2), int64(1), object(1)
memory usage: 475.0+ bytes


In [256]:
# Convert between DataFrame and 'Dict'
df3 = df.to_dict(); df3 # as data frame (dict)

{'Name': {0: 'John', 1: 'Sarah', 2: 'Zach', 3: 'Beth', 4: 'Lachlan'},
 'Age': {0: 35, 1: 28, 2: 33, 3: 55, 4: 43},
 'Gender': {0: 'Male', 1: 'Female', 2: 'Male', 3: 'Female', 4: 'Male'},
 'Coffee_Drinker': {0: True, 1: True, 2: False, 3: True, 4: False},
 'Diabetes': {0: 'Yes', 1: 'No', 2: 'No', 3: 'No', 4: 'Yes'}}

In [258]:
df4 = pd.DataFrame(df3); df4  # as DataFrame

Name  Age  Gender  Coffee_Drinker Diabetes
0     John   35    Male            True      Yes
1    Sarah   28  Female            True       No
2     Zach   33    Male           False       No
3     Beth   55  Female            True       No
4  Lachlan   43    Male           False      Yes

---
#### **1.3.5 Advance lists operations**
List can be a collecion of multiple Data Structures. For example:

In [261]:
# Lists in Python (can contain different types)
list1 = [c, Mat_A, df]
list1

[[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
       Name  Age  Gender  Coffee_Drinker Diabetes
 0     John   35    Male            True      Yes
 1    Sarah   28  Female            True       No
 2     Zach   33    Male           False       No
 3     Beth   55  Female            True       No
 4  Lachlan   43    Male           False      Yes]

In [263]:
# Examine the structure of the list and its components
for i, item in enumerate(list1):
    print(f'Component {i+1} type: {type(item)}')

Component 1 type: <class 'list'>
Component 2 type: <class 'numpy.ndarray'>
Component 3 type: <class 'pandas.core.frame.DataFrame'>


In [265]:
# Access list components
list1[0]  # vector c

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [267]:
list1[1]  # matrix Mat_A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [269]:
list1[2]  # data frame df

Name  Age  Gender  Coffee_Drinker Diabetes
0     John   35    Male            True      Yes
1    Sarah   28  Female            True       No
2     Zach   33    Male           False       No
3     Beth   55  Female            True       No
4  Lachlan   43    Male           False      Yes

In [271]:
# Create a dictionary (named list) in Python
list1 = {'VecC': c, 'MatA': Mat_A, 'DatFrame': df}
list1

{'VecC': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
 'MatA': array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 'DatFrame':       Name  Age  Gender  Coffee_Drinker Diabetes
 0     John   35    Male            True      Yes
 1    Sarah   28  Female            True       No
 2     Zach   33    Male           False       No
 3     Beth   55  Female            True       No
 4  Lachlan   43    Male           False      Yes}

In [273]:
# Examine the structure of the dictionary
for k, v in list1.items():
    print(f'{k}: {type(v)}')

VecC: <class 'list'>
MatA: <class 'numpy.ndarray'>
DatFrame: <class 'pandas.core.frame.DataFrame'>


In [275]:
# Access dictionary components
list1['VecC']  # vector component

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [277]:
list1['MatA']  # matrix component

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [279]:
list1['DatFrame']  # data frame component

Name  Age  Gender  Coffee_Drinker Diabetes
0     John   35    Male            True      Yes
1    Sarah   28  Female            True       No
2     Zach   33    Male           False       No
3     Beth   55  Female            True       No
4  Lachlan   43    Male           False      Yes

---
### **1.4 Type Conversion**

Python allows implicit and explicit type conversions. However, Python typically avoids implicit conversion between non-numeric types.

#### **1.4.1 Explicit Type Conversion**

In [283]:
int("42")        # String → Integer → 42

42

In [285]:
float(True)      # Boolean → Float → 1.0

1.0

In [287]:
str(3.14)        # Float → String → "3.14"

'3.14'

In [289]:
list((1, 2))     # Tuple → List → [1, 2]

[1, 2]

#### **1.4.2 Implicit Type Conversion**

General Rule: bool → int → float → complex

In [292]:
True + 5      # bool→int → 6

6

In [294]:
3 + 5.0       # int→float → 8.0

8.0

In [296]:
2.5 + 3j      # float→complex → (2.5+3j)

(2.5+3j)

In [298]:
mixed1 = (1 , 'a'); mixed1 # integer and string

(1, 'a')

In [300]:
type(mixed1)

tuple

In [302]:
list_mixed2 = [True, 'a']  # logical value coerced to string in R, but not in Python
list_mixed2

[True, 'a']

In [304]:
list_mixed3 = [True, 1]  # logical value is coerced to numeric in R, in Python True==1
list_mixed3

[True, 1]

In [306]:
# All elements are coerced to string in numpy array if types differ
nparray = np.array([5, False, 4.6, 'No']); nparray

array(['5', 'False', '4.6', 'No'], dtype='<U32')